/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.michielbdejong.litewrite.note'

type $nsid = typeof $nsid

export { $nsid }

/** A single litewrite note. Records live in the author's public repo and are world-readable. */
type Main = {
  $type: 'com.michielbdejong.litewrite.note'

  /**
   * The note body.
   */
  text: string

  /**
   * Optional note title.
   */
  title?: string

  /**
   * When the note was first created.
   */
  createdAt: l.DatetimeString

  /**
   * When the note was last edited.
   */
  updatedAt?: l.DatetimeString
}

export type { Main }

/** A single litewrite note. Records live in the author's public repo and are world-readable. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    text: /*#__PURE__*/ l.string({ maxLength: 100000 }),
    title: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 300 })),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
    updatedAt: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'datetime' }),
    ),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
